set_min_soc:
  fields:
    device_sn:
      required: true
      selector:
        text:
    min_soc:
      selector:
        number:
          min: 0
          max: 100
          mode: box
    min_soc_on_grid:
      name: Cut-Off SOC
      description: FoxESS minimum battery SOC while grid-connected.
      selector:
        number:
          min: 0
          max: 100
          mode: box
set_charge_periods:
  fields:
    device_sn:
      required: true
      selector:
        text:
    charge_from_grid1:
      name: Charge From Grid Period 1
      description: Allow grid charging during force-charge window 1.
      selector:
        boolean:
    start_time1:
      name: Force Charge Window 1 Start
      selector:
        time:
    end_time1:
      name: Force Charge Window 1 End
      selector:
        time:
    charge_from_grid2:
      name: Charge From Grid Period 2
      description: Allow grid charging during force-charge window 2.
      selector:
        boolean:
    start_time2:
      name: Force Charge Window 2 Start
      selector:
        time:
    end_time2:
      name: Force Charge Window 2 End
      selector:
        time:
set_device_setting:
  fields:
    device_sn:
      required: true
      selector:
        text:
    key:
      required: true
      selector:
        text:
    value:
      required: true
      selector:
        text:
