set_min_soc:
  fields:
    device_sn:
      required: true
      selector:
        text:
    min_soc:
      name: System Minimum SOC
      description: FoxESS `minSoc`. The system-wide minimum battery reserve.
      selector:
        number:
          min: 0
          max: 100
          mode: box
    min_soc_on_grid:
      name: Battery Cut-Off SOC
      description: FoxESS `minSocOnGrid`. The battery reserve used while grid-connected.
      selector:
        number:
          min: 0
          max: 100
          mode: box
